// =============================================================================
// AndroidNativeBridge.cs
//
// CONTROLLING-AGENT NOTE — first dotnet-build iteration:
//
// The `Native.*` namespace below refers to the generated C# wrappers around
// the Phase 3D AAR's Kotlin types. The exact AQNs depend on what the .NET 10
// Android binding generator emits after applying Transforms/Metadata.xml.
// The plan (Task 6) explicitly calls for 2-3 dotnet-build cycles to settle
// this — first run reveals the actual generated names, then we iterate
// Metadata.xml + this file until the surface is clean.
//
// Until that iteration runs on a Mac/Linux runner with the AAR fetched,
// this file references types that don't yet exist in the assembly. We gate
// the body behind `BINDINGS_GENERATED` so the bare csproj compile (no AAR
// fetched yet) succeeds with an empty assembly — facade fall-through to
// UnsupportedPlatformBridge handles the missing-binding case gracefully.
//
// To enable: pass `-p:DefineConstants=BINDINGS_GENERATED` to dotnet build
// once the AAR is in place at native/dvai-bridge-2.4.0.aar AND the
// generated wrappers compile cleanly. The CI workflow
// (.github/workflows/test-dotnet.yml) sets this for the binding-build job.
// =============================================================================

using System;
using System.Threading;
using System.Threading.Tasks;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DVAIBridge.Tests")]

namespace DVAIBridge.Android;

#if BINDINGS_GENERATED

/// <summary>
/// Android-side implementation of <see cref="INativeBridge"/>. Calls the
/// generated Java/Kotlin bindings under
/// <c>Co.Deepvoiceai.Bridge.NativeDVAIBridge</c> (renamed from the Kotlin
/// <c>co.deepvoiceai.bridge.DVAIBridge</c> object via Transforms/Metadata.xml).
/// </summary>
/// <remarks>
/// <para>
/// Resolved at runtime by <c>PlatformBridgeFactory.Create()</c> via
/// <c>Type.GetType("DVAIBridge.Android.AndroidNativeBridge, DVAIBridge.Android")</c>.
/// </para>
/// <para>
/// The <c>NativeDVAIBridge</c> bound type is referenced via dynamic-via-
/// reflection lookup until the binding generator settles on the exact AQN
/// shape; the actual call sites are stubbed below with TODO markers
/// flagged for the first <c>dotnet build</c> cycle (see Task 6 in the
/// plan: "expect 2-3 dotnet-build cycles" while iterating Metadata.xml).
/// The shape of every method is fixed by <see cref="INativeBridge"/>; only
/// the inner binding-generated call site changes per iteration.
/// </para>
/// </remarks>
internal sealed class AndroidNativeBridge : INativeBridge
{
    public AndroidNativeBridge()
    {
        // The Phase 3D AAR's `DVAIBridge.init(applicationContext)` MUST be
        // called once from the consumer app's `Application.onCreate()`.
        // The .NET facade can't know the application's Context (no MAUI/Avalonia
        // dependency); we trust the consumer's MAUI startup hooks
        // (e.g. `MauiAppBuilder.UseMauiApp<App>().ConfigureLifecycleEvents`)
        // to wire `DVAIBridge.Android.Bootstrap.Init(context)` per the
        // documented quickstart in `docs/guide/dotnet-sdk.md`.
    }

    public async Task<BoundServer> StartAsync(StartOptions opts, CancellationToken ct)
    {
        try
        {
            // The bound NativeDVAIBridge.StartAsync(opts) signature is
            // generated by the Java binding generator from the Kotlin
            // `suspend fun start(opts: StartOptions): BoundServer`.
            // Final shape resolves on the first build cycle once the
            // Metadata.xml transforms settle.
            var nativeOpts = StartOptionsToNative(opts);
            var nativeServer = await Native.NativeDVAIBridge.StartAsync(nativeOpts).ConfigureAwait(false);
            return NativeBoundServerToManaged(nativeServer);
        }
        catch (Java.Lang.Throwable e)
        {
            throw MapJavaThrowable(e);
        }
    }

    public async Task StopAsync(CancellationToken ct)
    {
        try
        {
            await Native.NativeDVAIBridge.StopAsync().ConfigureAwait(false);
        }
        catch (Java.Lang.Throwable e)
        {
            throw MapJavaThrowable(e);
        }
    }

    public Task<StatusInfo> GetStatusAsync(CancellationToken ct)
    {
        try
        {
            // status() is a synchronous (non-suspend) Kotlin function; bound
            // as a plain C# method by the binding generator.
            var native = Native.NativeDVAIBridge.Status();
            return Task.FromResult(NativeStatusInfoToManaged(native));
        }
        catch (Java.Lang.Throwable e)
        {
            return Task.FromException<StatusInfo>(MapJavaThrowable(e));
        }
    }

    public async Task<DownloadResult> DownloadModelAsync(DownloadOptions opts, CancellationToken ct)
    {
        try
        {
            var nativeOpts = DownloadOptionsToNative(opts);
            var nativeResult = await Native.NativeDVAIBridge.DownloadModelAsync(nativeOpts).ConfigureAwait(false);
            return NativeDownloadResultToManaged(nativeResult);
        }
        catch (Java.Lang.Throwable e)
        {
            throw MapJavaThrowable(e);
        }
    }

    public IDisposable SubscribeProgress(Action<ProgressEvent> handler)
    {
        // The Phase 3D AAR exposes both:
        //   - progressFlow : SharedFlow<ProgressEvent>      (Kotlin idiomatic)
        //   - addProgressListener / removeProgressListener (Java-friendly)
        // We use the Java-friendly listener path because the bound IFlow
        // wrapper is awkward in C# (the binding generator emits a clunky
        // shape for SharedFlow<T>; see plan Risk #5).
        var listener = new ProgressListenerAdapter(handler);
        Native.NativeDVAIBridge.AddProgressListener(listener);
        return new ListenerDisposable(listener);
    }

    // ------------------------------------------------------------------
    // Marshalling stubs — bodies finalize on the first dotnet build cycle.
    // The shape (parameter names + return types) is fixed; the inner
    // type references resolve once Metadata.xml stabilises the bound surface.
    // ------------------------------------------------------------------

    private static Native.StartOptions StartOptionsToNative(StartOptions opts)
    {
        // The bound StartOptions Kotlin data class has a builder-style
        // generated C# wrapper. Set every non-null field on the wrapper.
        var native = new Native.StartOptions();
        native.Backend = ParseNativeBackend(opts.Backend);
        if (opts.ModelPath is { } v) native.ModelPath = v;
        if (opts.TokenizerPath is { } v2) native.TokenizerPath = v2;
        if (opts.MmprojPath is { } v3) native.MmprojPath = v3;
        if (opts.ChatTemplate is { } v4) native.ChatTemplate = v4;
        if (opts.ModelId is { } v5) native.ModelId = v5;
        if (opts.ContextSize is { } v6) native.ContextSize = v6;
        if (opts.Threads is { } v7) native.Threads = v7;
        if (opts.GpuLayers is { } v8) native.GpuLayers = v8;
        if (opts.HttpBasePort is { } v9) native.HttpBasePort = v9;
        if (opts.HttpMaxPortAttempts is { } v10) native.HttpMaxPortAttempts = v10;
        if (opts.CorsOrigin is { } v11) native.CorsOrigin = v11;
        if (opts.Temperature is { } v12) native.Temperature = (float)v12;
        if (opts.TopP is { } v13) native.TopP = (float)v13;
        if (opts.TopK is { } v14) native.TopK = v14;
        if (opts.MaxNewTokens is { } v15) native.MaxNewTokens = v15;
        native.EmbeddingMode = opts.EmbeddingMode;
        native.VisionEnabled = opts.VisionEnabled;
        return native;
    }

    private static Native.DownloadOptions DownloadOptionsToNative(DownloadOptions opts)
    {
        return new Native.DownloadOptions
        {
            Url = opts.Url,
            Sha256 = opts.Sha256,
            DestFilename = opts.DestFilename ?? string.Empty,
        };
    }

    private static BoundServer NativeBoundServerToManaged(Native.BoundServer native) =>
        new(
            BaseUrl: native.BaseUrl,
            Port: native.Port,
            Backend: ParseManagedBackend(native.Backend),
            ModelId: native.ModelId);

    private static StatusInfo NativeStatusInfoToManaged(Native.StatusInfo native) =>
        new(
            Running: native.Running,
            BaseUrl: native.BaseUrl,
            Port: native.Port,
            Backend: native.Backend is null ? null : ParseManagedBackend(native.Backend),
            ModelId: native.ModelId);

    private static DownloadResult NativeDownloadResultToManaged(Native.DownloadResult native) =>
        new(
            Path: native.Path,
            Sha256: native.Sha256,
            SizeBytes: native.SizeBytes);

    private static Native.BackendKind ParseNativeBackend(BackendKind k) => k switch
    {
        BackendKind.Auto => Native.BackendKind.Auto,
        BackendKind.Llama => Native.BackendKind.Llama,
        BackendKind.MediaPipe => Native.BackendKind.MediaPipe,
        BackendKind.LiteRT => Native.BackendKind.LiteRT,
        // iOS-only backends raised earlier in the facade — defense in depth.
        _ => throw DVAIBridgeException.BackendUnavailable(k, $"{k} is iOS-only and not supported on Android."),
    };

    private static BackendKind ParseManagedBackend(Native.BackendKind k) => k switch
    {
        Native.BackendKind.Auto => BackendKind.Auto,
        Native.BackendKind.Llama => BackendKind.Llama,
        Native.BackendKind.MediaPipe => BackendKind.MediaPipe,
        Native.BackendKind.LiteRT => BackendKind.LiteRT,
        _ => BackendKind.Auto,
    };

    private static DVAIBridgeException MapJavaThrowable(Java.Lang.Throwable e)
    {
        // The Phase 3D AAR's DVAIBridgeError sealed class binds as a
        // hierarchy of Java throwables. Each subclass carries a JNI-bound
        // C# wrapper (Co.Deepvoiceai.Bridge.DVAIBridgeError$AlreadyStarted, etc.).
        // We pattern-match on the wrapper types to map back to the public
        // DVAIBridgeException factories.
        return e switch
        {
            Native.DVAIBridgeError.AlreadyStarted ase =>
                DVAIBridgeException.AlreadyStarted(ParseManagedBackend(ase.CurrentBackend), ase.BaseUrl),
            Native.DVAIBridgeError.ConfigurationInvalid ci =>
                DVAIBridgeException.ConfigurationInvalid(ci.Reason ?? string.Empty),
            Native.DVAIBridgeError.ModelLoadFailed mlf =>
                DVAIBridgeException.ModelLoadFailed(mlf.Reason ?? string.Empty),
            Native.DVAIBridgeError.BackendUnavailable bu =>
                DVAIBridgeException.BackendUnavailable(ParseManagedBackend(bu.Backend), bu.Reason ?? string.Empty),
            Native.DVAIBridgeError.ChecksumMismatch cm =>
                DVAIBridgeException.ChecksumMismatch(cm.Expected ?? string.Empty, cm.Got ?? string.Empty),
            Native.DVAIBridgeError.DownloadFailed df =>
                DVAIBridgeException.DownloadFailed(df.Reason ?? string.Empty),
            Native.DVAIBridgeError.BackendError be =>
                DVAIBridgeException.BackendError(be.Message ?? string.Empty),
            _ => DVAIBridgeException.BackendError(e.Message ?? "Unknown native error"),
        };
    }

    /// <summary>
    /// Adapts the Java <c>ProgressListener</c> interface to a C# delegate.
    /// </summary>
    private sealed class ProgressListenerAdapter : Java.Lang.Object, Native.IProgressListener
    {
        private readonly Action<ProgressEvent> _handler;

        public ProgressListenerAdapter(Action<ProgressEvent> handler)
        {
            _handler = handler;
        }

        public void OnProgressEvent(Native.ProgressEvent ev)
        {
            _handler(NativeProgressEventToManaged(ev));
        }

        private static ProgressEvent NativeProgressEventToManaged(Native.ProgressEvent ev) =>
            new(
                Kind: ParseProgressKind(ev),
                Phase: ParseProgressPhase(ev.Phase),
                Percent: ev.Percent >= 0 ? ev.Percent * 100.0 : null,
                Message: ev.Message,
                ErrorKind: ev is Native.ProgressEvent.Failed f ? f.Error?.JavaCast<Native.DVAIBridgeError>()?.Class.SimpleName : null,
                ErrorMessage: (ev as Native.ProgressEvent.Failed)?.Error?.Message);

        private static ProgressKind ParseProgressKind(Native.ProgressEvent ev) => ev switch
        {
            Native.ProgressEvent.Started => ProgressKind.Started,
            Native.ProgressEvent.Progress => ProgressKind.Progress,
            Native.ProgressEvent.Completed => ProgressKind.Completed,
            Native.ProgressEvent.Failed => ProgressKind.Failed,
            _ => ProgressKind.Progress,
        };

        private static ProgressPhase ParseProgressPhase(string s) => s switch
        {
            "start" => ProgressPhase.Start,
            "stop" => ProgressPhase.Stop,
            "download" => ProgressPhase.Download,
            "load" => ProgressPhase.Load,
            "ready" => ProgressPhase.Ready,
            "verify" => ProgressPhase.Verify,
            "error" => ProgressPhase.Error,
            _ => ProgressPhase.Load,
        };
    }

    private sealed class ListenerDisposable : IDisposable
    {
        private ProgressListenerAdapter? _listener;

        public ListenerDisposable(ProgressListenerAdapter listener)
        {
            _listener = listener;
        }

        public void Dispose()
        {
            if (_listener is { } l)
            {
                Native.NativeDVAIBridge.RemoveProgressListener(l);
                l.Dispose();
                _listener = null;
            }
        }
    }
}

/// <summary>
/// One-time bootstrap helper. Consumers must call
/// <see cref="Init(global::Android.Content.Context)"/> from
/// <c>Application.OnCreate</c> (MAUI: <c>MauiApplication</c>'s
/// <c>OnCreate</c> override) before the first <see cref="DVAIBridge.StartAsync"/>
/// or <see cref="DVAIBridge.DownloadModelAsync"/> call. Idempotent.
/// </summary>
public static class Bootstrap
{
    /// <summary>
    /// Stash an <see cref="global::Android.Content.Context"/> on the underlying
    /// <c>NativeDVAIBridge</c> object. Required for the MediaPipe backend
    /// and for <see cref="DVAIBridge.DownloadModelAsync"/>.
    /// </summary>
    public static void Init(global::Android.Content.Context applicationContext)
    {
        Native.NativeDVAIBridge.Init(applicationContext);
    }
}

#else // !BINDINGS_GENERATED — placeholder when the AAR hasn't been fetched yet.

/// <summary>
/// Placeholder Bootstrap class. Real implementation under
/// <c>BINDINGS_GENERATED</c> compile flag (see header comment for
/// activation steps). Until the AAR is fetched and the binding generator
/// has run, this no-op preserves the public API surface so consumer
/// MAUI csprojs that reference <see cref="DVAIBridge.Android"/> compile
/// without errors.
/// </summary>
public static class Bootstrap
{
    /// <summary>No-op until BINDINGS_GENERATED is defined.</summary>
    public static void Init(global::Android.Content.Context applicationContext) { }
}

#endif // BINDINGS_GENERATED
